// <auto-generated />
namespace FastKDS.DAL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddInvoNoToOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInvoNoToOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "202311290512520_AddInvoNoToOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
